### ISSUE TITLE
clicking the backdrop while trying to create a new wallet crashes the app

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#1003]
![Screenshot from 2022-06-22 18-15-12](https://user-images.githubusercontent.com/25265396/175098132-ccf178a8-f331-49b3-8a64-9d87700f4d3c.png)

From the picture above, the modal presented is for creating a new wallet. Clicking the backdrop or clicking the cancel button causes the app to crash.

See log below:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11f6554]

goroutine 15 [running]:
github.com/planetdecred/godcr/ui/modal.(*CreatePasswordModal).Handle(0xc002984400)
        /home/kennedy/Projects/src/github.com/dreacot/godcr/ui/modal/create_password_modal.go:219 +0x814
github.com/planetdecred/godcr/ui.(*Window).displayWindow(0xc00015c000, {{0xc0a4f184141df208, 0x20f6f2f8f5, 0x2f31380}, {0x3f800000, 0x3f800000}, {0x320, 0x2bc}, {0x0, 0x0, ...}, ...})
        /home/kennedy/Projects/src/github.com/dreacot/godcr/ui/window.go:176 +0x10e
github.com/planetdecred/godcr/ui.(*Window).HandleEvents(0xc00015c000)
        /home/kennedy/Projects/src/github.com/dreacot/godcr/ui/window.go:148 +0x156
main.main.func2()
        /home/kennedy/Projects/src/github.com/dreacot/godcr/main.go:80 +0x26
created by main.main
        /home/kennedy/Projects/src/github.com/dreacot/godcr/main.go:79 +0x4d2
exit status 2
```

**Comment by Sirmorrison** [comment]
This should be resolved by #996.
