### ISSUE TITLE
nil pointer dereference in dcrwallet's p2p package

### ISSUE THREAD

**Issue by jrick** [planetdecred/godcr#454]
Saw this doing an initial sync built from master (currently, f97d02e907e71d4cadff10b4170a1e7cf7379092):

```
2021-06-01 15:33:45.963 [INF] DLWL: [1] Connected 2000 blocks, new tip 00000010f726b36c154e0c2fc9bf0ec84b2a231fe385a428979ec62a5f667190, height 246000, date 2019-08-12 00:14:31 -0400 EDT
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1449173]

goroutine 117 [running]:
decred.org/dcrwallet/p2p.(*RemotePeer).writeMessages.func1(0xc000a4e1c0, 0xc0001a5740)
        /home/jrick/go/pkg/mod/decred.org/dcrwallet@v1.6.0-rc4/p2p/peering.go:418 +0xb3
created by decred.org/dcrwallet/p2p.(*RemotePeer).writeMessages
        /home/jrick/go/pkg/mod/decred.org/dcrwallet@v1.6.0-rc4/p2p/peering.go:404 +0x7c
```

Haven't dug into the details but at the very least that is an outdated version of the dcrwallet module.  Perhaps it just needs an update to the latest patch release.

**Comment by oshorefueled** [comment]
#476 resolves this
