### ISSUE TITLE
success message doesn't show after successfully copying to the clipboard

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#502]
1. Currently while clicking on the copy icon, the wallet log gets copied, but there's no message to inform the user that the log has been copied
<img width="802" alt="Screenshot 2021-06-30 at 3 51 34 PM" src="https://user-images.githubusercontent.com/25265396/123982573-0d4a0a80-d9bb-11eb-8c41-056ffdf831c7.png">

2. Clicking the copy button several times causes the app to crash, below is the log

```
panic: runtime error: index out of range [56] with length 25

goroutine 66 [running]:
gioui.org/internal/opconst.OpType.Size(...)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/internal/opconst/ops.go:107
gioui.org/internal/ops.(*Reader).Decode(0xc00097a718, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/internal/ops/reader.go:122 +0xae5
gioui.org/io/router.(*Router).collect(0xc00097a490)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/io/router/router.go:123 +0x167
gioui.org/io/router.(*Router).Frame(0xc00097a490, 0xc00020e780)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/io/router/router.go:72 +0x14d
gioui.org/app.(*Window).processFrame(0xc00097a400, 0xc02f3f2439408e20, 0xae65aee44, 0x59958a0, 0x640, 0x4b0, 0xc00020e780)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/app/window.go:164 +0xf3
gioui.org/app.(*Window).validateAndProcess(0xc00097a400, 0xc02f3f2439408e20, 0xae65aee44, 0x59958a0, 0x640, 0x4b0, 0x1, 0xc00020e780, 0x0, 0x0)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/app/window.go:148 +0xcb
gioui.org/app.(*Window).run(0xc00097a400, 0xc000364c30)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/app/window.go:412 +0x811
created by gioui.org/app.NewWindow
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/app/window.go:107 +0x295
```

3. On the transaction details page, clicking the blue text doesn't show a success message when the text is copied
<img width="597" alt="Screenshot 2021-06-30 at 4 40 40 PM" src="https://user-images.githubusercontent.com/25265396/123990710-eb07bb00-d9c1-11eb-930f-e84945982054.png">

**Comment by Sirmorrison** [comment]
When the page first loads, this is the display on windows though.
![image](https://user-images.githubusercontent.com/27733432/130056054-3fa05d0e-c7e8-4db1-9677-26347040c8d6.png)
