### ISSUE TITLE
clicking the edit account icon crashes the app

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#506]
trying to edit the account name causes the app to crash
<img width="804" alt="Screenshot 2021-06-30 at 4 29 40 PM" src="https://user-images.githubusercontent.com/25265396/123988983-61a3b900-d9c0-11eb-8ba9-c594ec67dbab.png">

below is the log

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4a4ed8c]

goroutine 42 [running]:
github.com/planetdecred/godcr/ui.pageCommon.subpageEventHandler(0xc00001a0a0, 0xc0006166c0, 0xc0002fe070, 0xc000540890, 0xc000540820, 0xc0000ac5a0, 0xc0005a0500, 0xc0005a0550, 0xc0005a05a0, 0xc0005a05f0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/page.go:628 +0xec
github.com/planetdecred/godcr/ui.pageCommon.subpageHeader(0xc00001a0a0, 0xc0006166c0, 0xc0002fe070, 0xc000540890, 0xc000540820, 0xc0000ac5a0, 0xc0005a0500, 0xc0005a0550, 0xc0005a05a0, 0xc0005a05f0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/page.go:542 +0xf8
github.com/planetdecred/godcr/ui.pageCommon.SubPageLayout.func1.1(0x0, 0x0, 0x440, 0x3bb, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, 0x59958a0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/page.go:534 +0x138
gioui.org/layout.Inset.Layout(0x0, 0x0, 0x141700000, 0x0, 0x0, 0x0, 0x440, 0x3bb, 0x4000000040000000, 0x5114060, ...)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/layout/layout.go:147 +0x4e4
github.com/planetdecred/godcr/ui.pageCommon.SubPageLayout.func1(0x0, 0x0, 0x440, 0x3d9, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, 0x59958a0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/page.go:533 +0x125
gioui.org/layout.Flex.Layout(0x4000001, 0x0, 0x0, 0x440, 0x3d9, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, ...)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/layout/flex.go:99 +0xcb5
github.com/planetdecred/godcr/ui.pageCommon.SubPageLayout(0xc00001a0a0, 0xc0006166c0, 0xc0002fe070, 0xc000540890, 0xc000540820, 0xc0000ac5a0, 0xc0005a0500, 0xc0005a0550, 0xc0005a05a0, 0xc0005a05f0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/page.go:531 +0x258
github.com/planetdecred/godcr/ui.(*acctDetailsPage).Layout.func4(0x0, 0x0, 0x440, 0x3d9, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, 0x59958a0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/account_details_page.go:103 +0x298
gioui.org/layout.Inset.Layout(0x141c00000, 0x141c00000, 0x141c00000, 0x141c00000, 0x0, 0x0, 0x440, 0x3d9, 0x4000000040000000, 0x5114060, ...)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/layout/layout.go:147 +0x4e4
github.com/planetdecred/godcr/ui.pageCommon.UniformPadding(...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/page.go:514
github.com/planetdecred/godcr/ui.(*acctDetailsPage).Layout.func5(0x0, 0x0, 0x4a0, 0x439, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, 0x59958a0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/account_details_page.go:106 +0xe5
gioui.org/layout.Flex.Layout(0x4000000, 0x0, 0x0, 0x640, 0x439, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, ...)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/layout/flex.go:99 +0xcb5
github.com/planetdecred/godcr/ui.pageCommon.Layout.func1.1(0x0, 0x0, 0x640, 0x439, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, 0x59958a0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/page.go:439 +0x1dd
gioui.org/layout.Flex.Layout(0x4000001, 0x0, 0x0, 0x640, 0x4b0, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, ...)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/layout/flex.go:99 +0xcb5
github.com/planetdecred/godcr/ui.pageCommon.Layout.func1(0x0, 0x0, 0x640, 0x4b0, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, 0x59958a0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/page.go:436 +0x258
gioui.org/layout.Stack.Layout(0x4ccb000, 0x0, 0x0, 0x640, 0x4b0, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, ...)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/layout/stack.go:78 +0x616
github.com/planetdecred/godcr/ui.pageCommon.Layout(0xc00001a0a0, 0xc0006166c0, 0xc0002fe070, 0xc000540890, 0xc000540820, 0xc0000ac5a0, 0xc0005a0500, 0xc0005a0550, 0xc0005a05a0, 0xc0005a05f0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/page.go:429 +0x497
github.com/planetdecred/godcr/ui.(*acctDetailsPage).Layout(0xc0000fed00, 0x0, 0x0, 0x640, 0x4b0, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/account_details_page.go:105 +0x326
github.com/planetdecred/godcr/ui.(*Window).layoutPage.func2(0x0, 0x0, 0x640, 0x4b0, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, 0x59958a0, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/window.go:157 +0x95
gioui.org/layout.Stack.Layout(0x4ccb101, 0x640, 0x4b0, 0x640, 0x4b0, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, ...)
        /Users/kennedy/go/pkg/mod/gioui.org@v0.0.0-20210418151603-3b69b5ed0512/layout/stack.go:60 +0x7d5
github.com/planetdecred/godcr/ui.(*Window).layoutPage(0xc000540780, 0x640, 0x4b0, 0x640, 0x4b0, 0x4000000040000000, 0x5114060, 0xc00056c490, 0xc02f41412b1d1048, 0x15cdfaf550f, ...)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/window.go:151 +0x257
github.com/planetdecred/godcr/ui.(*Window).Loop(0xc000540780, 0xc000969c20)
        /Users/kennedy/go/src/github.com/planetdecred/godcr/ui/window.go:255 +0x4c5
created by main.main
        /Users/kennedy/go/src/github.com/planetdecred/godcr/main.go:92 +0x51c
```

**Comment by dreacot** [comment]
this error no longer exists on the latest master commit
