### ISSUE TITLE
removing a watch only wallet crashed the app

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#941]
If the watch only wallet is the only wallet in the list, attempting to delete it, causes the app to crash

```
2022-05-22 21:17:26.515 [INF] DLWL: Deleting Wallet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15225d4]

goroutine 25 [running]:
github.com/planetdecred/godcr/ui.(*Window).drawWindowUI(0xc0001d84b0, 0x320, 0x258, 0x320, 0x258, 0x3f8000003f800000, 0x1f2c780, 0xc0004bd718, 0xc09ac4759eb3f690, 0xadb25b05c1, ...)
        /home/kennedy/Projects/src/github.com/dreacot/godcr/ui/window.go:264 +0x154
github.com/planetdecred/godcr/ui.(*Window).displayWindow(0xc0001d84b0, 0xc09ac4759eb3f690, 0xadb25b05c1, 0x2cea180, 0x3f8000003f800000, 0x320, 0x258, 0x0, 0x0, 0x0, ...)
        /home/kennedy/Projects/src/github.com/dreacot/godcr/ui/window.go:224 +0x198
github.com/planetdecred/godcr/ui.(*Window).HandleEvents(0xc0001d84b0)
        /home/kennedy/Projects/src/github.com/dreacot/godcr/ui/window.go:187 +0x198
main.main.func2(0xc0001d84b0, 0xc00023ad00)
        /home/kennedy/Projects/src/github.com/dreacot/godcr/main.go:80 +0x2b
created by main.main
        /home/kennedy/Projects/src/github.com/dreacot/godcr/main.go:79 +0x4c5
```

**Comment by Sirmorrison** [comment]
Resolved
